FROM python:3.12-slim

RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt /requirements.txt
RUN python -m pip install --upgrade pip \
    && pip install -r /requirements.txt gunicorn

COPY ./anubis /code/anubis
RUN mkdir -p /code/site

WORKDIR /code/anubis
ENV PYTHONPATH=/code
ENV GUNICORN_CMD_ARGS="--bind=0.0.0.0:8000 --workers=1 --thread=4 --worker-class=gthread --forwarded-allow-ips='*' --access-logfile -"
CMD ["gunicorn", "main:app"]

VOLUME ["/code/site"]
