FROM python:3.14-alpine3.22

RUN apk update && apk upgrade

COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt gunicorn
COPY ./anubis /code/anubis
RUN mkdir /code/site

ARG GIT_SHA=
ARG GIT_REF=
ENV GIT_SHA=${GIT_SHA}
ENV GIT_REF=${GIT_REF}

WORKDIR /code/anubis
ENV PYTHONPATH=/code

ENV GUNICORN_CMD_ARGS="--bind=0.0.0.0:8000 --workers=1 --thread=4 --worker-class=gthread --forwarded-allow-ips='*' --access-logfile -"
CMD ["gunicorn", "main:app"]

VOLUME ["/code/site"]
